version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: events-api
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    ports:
       - "8000:8000"
    environment:
      - "APP_NAME=Events-Api"
      - "APP_ENV=local"
      - "APP_DEBUG=false"
      - "APP_URL=http://localhost"
      - "APP_TIMEZONE=UTC"
