version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: events-api
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
       - "8000:8000"
